version: '3.8'

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.111.0
    container_name: otel-collector
    volumes:
      - ./config/otel-collector.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "1888:1888"    # pprof extension
      - "8888:8888"    # Prometheus metrics exposed by the Collector
      - "8889:8889"    # Prometheus exporter metrics
      - "13133:13133"  # health_check extension
      - "4317:4317"    # OTLP gRPC receiver
      - "4318:4318"    # OTLP HTTP receiver
      - "55679:55679"  # zpages extension
    networks:
      - otel-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - otel-net

  grafana:
    image: grafana/grafana-enterprise:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - otel-net
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"  # HTTP query and ingestion endpoint
    networks:
      - otel-net
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9412:9411"  # Zipkin UI and API
    networks:
      - otel-net

networks:
  otel-net:
    driver: bridge
